# ***importing Tensorflow Library***

In [3]:
import tensorflow as tf


# One Hot function
its a function which convert the values to vector 


In [4]:
from tensorflow.keras.preprocessing.text import one_hot

# Sentence making


In [5]:
sent=[
      'hello how are you',
      'i am fine and you',
      'i am arshad khan',
      'i am a Artificial intelegence engineer',
      'and also a software engineer'
]


# Preprocessing 


In [9]:
# Vocablaray size
voc_size = 100000

# One hot representation 
changing my above dictionary to one hot represntation

In [11]:
onhotRep=[one_hot(words, voc_size)for words in sent]
onhotRep

[[3204, 52826, 92168, 85646],
 [27198, 67976, 78216, 35051, 85646],
 [27198, 67976, 14548, 93286],
 [27198, 67976, 18569, 68955, 81966, 55662],
 [35051, 80422, 18569, 70363, 55662]]

# some librarie for embadding 

In [14]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
# for model
from tensorflow.keras.models import Sequential
# numpy for colculations
import numpy as np 

# The sentence lenght will make all the sentences in same length of vector


1.   pad_sequence is a function which take the one hot representation as a parameter

2.   padding = 'pre' meant the zero will added from left side it mean the zero will add before 
 padding = 'post' will add the zero after







In [18]:
sent_length=8

embedded_doc=pad_sequences(onhotRep ,padding='pre' , maxlen=sent_length)
print(embedded_doc)

[[    0     0     0     0  3204 52826 92168 85646]
 [    0     0     0 27198 67976 78216 35051 85646]
 [    0     0     0     0 27198 67976 14548 93286]
 [    0     0 27198 67976 18569 68955 81966 55662]
 [    0     0     0 35051 80422 18569 70363 55662]]


# Setting the Dimension


In [19]:
dim=10


# Executing the model 

1.   Embedding is a function taking three dimensions 




In [22]:
model = Sequential()
model.add(Embedding(voc_size,10, input_length=sent_length))
model.compile('adam','mse')

In [23]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             1000000   
Total params: 1,000,000
Trainable params: 1,000,000
Non-trainable params: 0
_________________________________________________________________


In [24]:
print(model.predict(embedded_doc))

[[[-0.00862781 -0.01702359  0.01955861 -0.00347314 -0.04669362
    0.00795398  0.03724721  0.00681498  0.00173718  0.03793389]
  [-0.00862781 -0.01702359  0.01955861 -0.00347314 -0.04669362
    0.00795398  0.03724721  0.00681498  0.00173718  0.03793389]
  [-0.00862781 -0.01702359  0.01955861 -0.00347314 -0.04669362
    0.00795398  0.03724721  0.00681498  0.00173718  0.03793389]
  [-0.00862781 -0.01702359  0.01955861 -0.00347314 -0.04669362
    0.00795398  0.03724721  0.00681498  0.00173718  0.03793389]
  [ 0.04480195 -0.00731986 -0.04164562  0.02325657 -0.02732551
    0.02113253 -0.04421614  0.04899609 -0.01349802  0.0367723 ]
  [ 0.0323787  -0.01674131  0.04493967 -0.02239465 -0.02821043
   -0.00464068  0.04397741 -0.01441727  0.00601236 -0.00277162]
  [-0.01211349 -0.04515188  0.02958522  0.02627471  0.01316195
    0.04962554 -0.04030726 -0.02685968 -0.0367819  -0.01196585]
  [-0.02491673  0.03150753 -0.03600498 -0.02616864 -0.04731878
    0.03759998 -0.01815303  0.01606521  0.010777

In [25]:
embedded_doc[0]

array([    0,     0,     0,     0,  3204, 52826, 92168, 85646],
      dtype=int32)

In [26]:
print(model.predict(embedded_doc)[0])

[[-0.00862781 -0.01702359  0.01955861 -0.00347314 -0.04669362  0.00795398
   0.03724721  0.00681498  0.00173718  0.03793389]
 [-0.00862781 -0.01702359  0.01955861 -0.00347314 -0.04669362  0.00795398
   0.03724721  0.00681498  0.00173718  0.03793389]
 [-0.00862781 -0.01702359  0.01955861 -0.00347314 -0.04669362  0.00795398
   0.03724721  0.00681498  0.00173718  0.03793389]
 [-0.00862781 -0.01702359  0.01955861 -0.00347314 -0.04669362  0.00795398
   0.03724721  0.00681498  0.00173718  0.03793389]
 [ 0.04480195 -0.00731986 -0.04164562  0.02325657 -0.02732551  0.02113253
  -0.04421614  0.04899609 -0.01349802  0.0367723 ]
 [ 0.0323787  -0.01674131  0.04493967 -0.02239465 -0.02821043 -0.00464068
   0.04397741 -0.01441727  0.00601236 -0.00277162]
 [-0.01211349 -0.04515188  0.02958522  0.02627471  0.01316195  0.04962554
  -0.04030726 -0.02685968 -0.0367819  -0.01196585]
 [-0.02491673  0.03150753 -0.03600498 -0.02616864 -0.04731878  0.03759998
  -0.01815303  0.01606521  0.0107775  -0.04622852]]